# Generated by Django 3.2 on 2021-05-06 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='row',
            name='game',
        ),
        migrations.DeleteModel(
            name='Square',
        ),
        migrations.DeleteModel(
            name='Row',
        ),
    ]
