# Generated by Django 3.2 on 2021-04-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='square',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='squares',
            field=models.ManyToManyField(related_name='game', to='game.Square'),
        ),
    ]
