# Generated by Django 3.2 on 2021-05-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210506_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='mode',
            field=models.BooleanField(default=True),
        ),
    ]
