# Generated by Django 3.2 on 2021-04-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210422_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='squares',
        ),
        migrations.RemoveField(
            model_name='row',
            name='col10_type',
        ),
        migrations.RemoveField(
            model_name='row',
            name='col10_visit',
        ),
        migrations.RemoveField(
            model_name='row',
            name='col1_type',
        ),
        migrations.RemoveField(
            model_name='row',
            name='col1_visit',
        ),
        migrations.RemoveField(
            model_name='row',
            name='col2_type',
        ),
        migrations.RemoveField(
            model_name='row',
            name='col2_visit',
        ),
        migrations.RemoveField(
            model_name='row',
            name='col3_type',
        ),
        migrations.RemoveField(
            model_name='row',
            name='col3_visit',
        ),
        migrations.RemoveField(
            model_name='row',
            name='col4_type',
        ),
        migrations.RemoveField(
            model_name='row',
            name='col4_visit',
        ),
        migrations.RemoveField(
            model_name='row',
            name='col5_type',
        ),
        migrations.RemoveField(
            model_name='row',
            name='col5_visit',
        ),
        migrations.RemoveField(
            model_name='row',
            name='col6_type',
        ),
        migrations.RemoveField(
            model_name='row',
            name='col6_visit',
        ),
        migrations.RemoveField(
            model_name='row',
            name='col7_type',
        ),
        migrations.RemoveField(
            model_name='row',
            name='col7_visit',
        ),
        migrations.RemoveField(
            model_name='row',
            name='col8_type',
        ),
        migrations.RemoveField(
            model_name='row',
            name='col8_visit',
        ),
        migrations.RemoveField(
            model_name='row',
            name='col9_type',
        ),
        migrations.RemoveField(
            model_name='row',
            name='col9_visit',
        ),
        migrations.AddField(
            model_name='row',
            name='type',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AddField(
            model_name='row',
            name='visit',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
