# Generated by Django 3.2 on 2021-04-22 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210422_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='row',
            name='visit',
        ),
    ]
