# Generated by Django 3.2 on 2021-04-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='type',
            field=models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=100),
        ),
    ]
