# Generated by Django 3.2 on 2021-04-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_game_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='keys',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
